steps:
  - name: gradle:jdk11
    entrypoint: gradle
    args: ["--no-daemon", "test"]
    dir: backend
  - name: gradle:jdk11
    entrypoint: gradle
    args: ["--no-daemon", "assemble"]
    dir: backend
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/lokaler.kaufen", "--build-arg=JAR_FILE=backend/build/libs/mercury-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/$PROJECT_ID/lokaler.kaufen"]
